# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [v1.x]

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Deno
      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: ${{ matrix.deno-version }}

      # Verify formatting
      - name: Verify Formatting
        run: deno fmt --check

      # Lint the code
      - name: Lint the code
        run: deno lint

      # Run tests
      - name: Run tests
        run: deno test

      # Upload lint results
      - name: Upload lint results
        uses: actions/upload-artifact@v4
        with:
          name: lint-results
          path: deno-lint-report.txt

      # Upload test results
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: deno-test-report.txt

  report:
    runs-on: ubuntu-latest
    needs: lint_and_test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download lint results
        uses: actions/download-artifact@v4
        with:
          name: lint-results

      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Display lint results
        run: |
          cat deno-lint-report.txt

      - name: Display test results
        run: |
          cat deno-test-report.txt

