name: Pylint

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyzing the code with pylint
        run: |
          pylint $(git ls-files '*.py') \
            --exit-zero

      - name: Upload pylint report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint-report.txt

  report:
    runs-on: ubuntu-latest
    needs: pylint

    steps:
      - name: Download pylint report
        uses: actions/download-artifact@v3
        with:
          name: pylint-report

      - name: Display pylint report
        run: |
          cat pylint-report.txt
